version: "3"
services:
  agent:
    image: icr.io/instana/agent
    pid: "host"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run:/run
      - /dev:/dev:ro
      - /sys:/sys:ro
      - /var/log:/var/log:ro
    networks:
      demomesh:
        aliases:
          - instana-agent
    environment:
      - INSTANA_AGENT_ENDPOINT=ingress-red-saas.instana.io
      - INSTANA_AGENT_ENDPOINT_PORT=443
      - INSTANA_AGENT_KEY=xxxxxxxxxxx
      - INSTANA_DOWNLOAD_KEY=xxxxxxxxxxxx
      - INSTANA_AGENT_ZONE=${agent_zone:-sdk-demo}
    expose:
      - 42699

  graphql:
    image: node:18-slim
    working_dir: /app
    command: bash -c "yarn dev"
    volumes:
      - ./graphql:/app:rw
    # build:
    #   context: ./receiver-app
    networks:
      demomesh:
        aliases:
          - receiver-app
    environment:
      - INSTANA_AGENT_HOST=agent
      - BIND_ADDRESS=0.0.0.0
    expose:
      - 4000
    ports:
      - 4000:4000
    depends_on:
      - agent

  # sender-app:
  #   build:
  #     context: ./sender-app
  #   networks:
  #     demomesh:
  #       aliases:
  #         - sender-app
  #   environment:
  #     - DOWNSTREAM_HOST=receiver-app
  #   depends_on:
  #     - receiver-app

networks:
  demomesh: {}
